name: deploy to ec2

on:
  workflow_run:
     workflows: ["Docker Image CI"]
     types:
        - completed

jobs:
    deploy:
        runs-on: ubuntu-latest
        
        if: ${{github.event.workflow_run.conclusion == 'success'}}

        steps:
        - name: Deploy to EC2
          uses: appleboy/ssh-action@master
          with:
            host: ${{secrets.EC2_HOST}}
            username: ${{secrets.EC2_USERNAME}}
            key:  ${{secrets.EC2_SSH_KEY}}
            script: |
                docker pull ramram27/node-app:latest
                docker rm -f node-app || true
                docker run -d --name node-app -p 4000:8080 ramram27/node-app:latest



